import torch
from torch import nn


class PID(nn.Module):
    r"""
    This class is the basic class for all PID controller implementations.
    """
    def __init__(self, parameters):
        device=parameters.device
        self.integrity_initialized = False
        self.integity = torch.zeros(1, device=device)
        self.parameters = parameters
        self.parameters.requires_grad = True
        pass

    def forward(self, state, ref_state, feed_forward_quantity=None):
        r"""
        Args:
            parameters: controller parameters, e.g. kp, ki, kd in PID controllers.
            state:  current system state of dynamic systems.
            ref_state:  the reference state of systems to reach.
            feed_forward_quantity: system plant input generated by other feed forward
                controllers.
        """
        pass

    def reset(self):
        r"""
        This method is used to reset the internal state.
        For example, integrated error in PID controller
        """
        # if self.integrity_initialized:

        # else:
